name: nextstrain
channels:
  - conda-forge
  - bioconda
  - defaults
dependencies:
  - mafft=7.505
  - iqtree=2.2.0_beta
  - nextalign=2.14.0
  - python>=3.10*
  - pip:
    - nextstrain-augur==22.1.0
