name: nextstrain
channels:
  - conda-forge
  - bioconda
  - defaults
dependencies:
  - augur=16.0.3
  - auspice=2.37.1
  - iqtree=2.2.0_beta
  - nextalign=2.3.0
  - nextclade=2.3.0
  - nextstrain-cli=4.1.1
  - python>=3.7*
